### ISSUE TITLE
fatal: this operation must be run in a work tree

### ISSUE THREAD

**Issue by chawinphat** [Andrew-Chen-Wang/github-wiki-action#76]
Hi, I'm trying to use this workflow, and this error is appearing. I'm using the default workflow and inputs specified.
Changing the strategy to input instead of clone made no difference. Any ideas on what could be the solution?

error messages:
Run Andrew-Chen-Wang/github-wiki-action@v4
Run "${GITHUB_ACTION_PATH%/}/src/$INPUT_STRATEGY.sh"
Initialized empty Git repository in /tmp/tmp.Haneogu7ZO/
fatal: this operation must be run in a work tree
Error: Process completed with exit code 128.

**Comment by StevenLooman** [comment]
While trying to use this action, I ran into the same error. The fix for me was to create the `wiki` directory (default value for parameter `path`) in the repository the action runs on. Note that - at the time of writing this comment - [v4.4.0](https://github.com/Andrew-Chen-Wang/github-wiki-action/releases/tag/v4.4.0) (v4) is significantly different that the current master/commit https://github.com/Andrew-Chen-Wang/github-wiki-action/commit/86138cbd6328b21d759e89ab6e6dd6a139b22270.

It turns out that the action (v4) works differently than I expected. I was expecting that this does a checkout of the `<repo>.wiki` repository. Then you apply your changes, if any. Finally, the action - in a post action hook - would commit/push the changes.

The way this actually works is that the files in the path specified by the `path` (`wiki` by default) are mirrored to the wiki-repository. This means that any files which are in the wiki-repository which are not in the `wiki` directory, are deleted.

The mentioned current master/commit https://github.com/Andrew-Chen-Wang/github-wiki-action/commit/86138cbd6328b21d759e89ab6e6dd6a139b22270 does a regular clone instead of a bare one and then **copies** all files from the `wiki` directory to wiki-clone and committed. Note that any existing files are **not** removed by this action. This works for my flow which mixes hand written files combined with automatic generated files.
