### ISSUE TITLE
Automatically transform in-source links to in-wiki links

### ISSUE THREAD

**Issue by ribtoks** [Andrew-Chen-Wang/github-wiki-action#8]
Hi

Thanks for developing **github-wiki-action**. There's a small problem with cross-links:

Steps to reproduce:

- create `docs/First.md` and `docs/Second.md`
- Add a link `[Second](./Second.md)` to the `First.md`
- The link works in GitHub UI
- Deploy Wiki
- The link does not work

**Comment by Andrew-Chen-Wang** [comment]
Sorry, I don't want to leave you hanging for too long like last time, but I've got finals coming up so I won't be able to return back until mid December when they're over. Apologies in advance.

**Comment by ribtoks** [comment]
@Andrew-Chen-Wang No problem and thanks for replying. Will be looking forward to your return.

**Comment by Andrew-Chen-Wang** [comment]
@ribtoks The error is not on this repository. Instead, GitHub wiki apparently follows MediaWiki's link syntax: https://stackoverflow.com/a/8972756

I've tested this with your example. Instead of `[First](./First.md)`, you instead have to do `[[First|First]]`. You can test this out in the edit pane.

**Comment by ribtoks** [comment]
@Andrew-Chen-Wang Thanks for investigating. I do not agree about usage of MediaWiki example right in the `.md` files because then links in the `.md` files stop to work. The whole point of this GitHub Action is to deploy `.md` files into Wiki. If you would ruin your `.md` files right away, then there's no difference from writing Wiki files right away. The purpose is to have both working `.md` files **and** Wiki.

**Comment by Andrew-Chen-Wang** [comment]
Hm in this case, a potential "loophole" is that in this action, I can create a quick regex and optionally change the links to be of MediaWiki format and commit the changes to the wiki git.

**Comment by ribtoks** [comment]
@Andrew-Chen-Wang Yes, changing links before the deploy sounds like a good idea!

**Comment by xabolcs** [comment]
> I've tested this with your example. Instead of `[First](./First.md)`, you instead have to do `[[First|First]]`. You can test this out in the edit pane.

The problem is not the markdown type linking!
The problem is that there is an extension (`.md`) in the link!

GitHub's wiki shows the page source if there is an extension in the link, like in `[link to Second page with extension](./Second.md)`.
If one drops the extensions, like in `[link to Second page without extension](Second)` then it will work on the GitHub wiki.

If one would strip the extensions from the links, then the title functionality should taken into account!
E.g.
```markdown
This is a test with a [link to other page](Second.md "a nice title with an .md inside" ).
```

**Comment by Andrew-Chen-Wang** [comment]
yes but `[link to other page]` is annoying sinve we'd want to use relative paths.

**Comment by xabolcs** [comment]
Thats why I wrote: the deploy script should just remove the extension from the link.
No need to reformat it to MediaWiki.

**Comment by jcbhmr** [comment]
@ribtoks do you have an opinion on whether you think this should be a separate preprocessing step/action or included in this Andrew-Chen-Wang/github-wiki-action ?

```yml
- uses: octocat/strip-md-links@v1
  with:
    path: wiki/**.md
- uses: Andrew-Chen-Wang/github-wiki-action@v4
```
vs
```yml
- uses: Andrew-Chen-Wang/github-wiki-action@v4
  with:
    strip_md_links: true
```

Related to #21 

/cc @xabolcs

**Comment by ribtoks** [comment]
I'd vote for the latter `strip_md_links: true`. It's possible that the `octocat/strip-md-links` will be gone, etc, but `github-wiki-action` will have it's own implementation, thus the user interface will not change.

**Comment by jcbhmr** [comment]
@ribtoks Maybe I'm misunderstanding, what do you mean by "change"? Do you mean that the action will auto-update? I don't think it does that since it's pinned at `@v1`.

**Comment by jcbhmr** [comment]
I assume that the issue outlined here is this:

```md
Check out our [How it works](./How-it-works.md) page!
```

That this 👆 doesn't work in the deployed GitHub wiki tab. That's because the URLs that GitHub wikis use are `/wiki/How-it-works`, not `/blob/main/wiki/How-it-works.md`. Thus, you need something like:

https://github.com/marketplace/actions/strip-markdown-extensions-from-links-action

```js
for (const file of readDirSync(filesPath)) {
  const filename: string = file.toString()
  const oldContent: string = readFileSync(filename, 'utf8')
  const newContent: string = replacer.transformMarkdownLinks(oldContent)

  if (oldContent != newContent) {
    debug(filename + ' updated')
    writeFileSync(filename, newContent)
  }
}
```

to solve the problem. Am I right?

I think that this problem is a great thing that we should highlight in our examples in the readme! We can point out https://github.com/marketplace/actions/strip-markdown-extensions-from-links-action like this:

> ### Preprocessing
>
> You may wish to strip the `[link](page.md)` `.md` suffix from your links to make them viewable in GitHub source view (with the `.md`) *as well as* in GitHub wiki (without the `.md`; pretty URLs!). You can use a preprocessing action like [Strip MarkDown extensions from links action](https://github.com/marketplace/actions/strip-markdown-extensions-from-links-action) to remove those `.md` suffixes before using this action. Here's an example:
>
> ```source-yaml
> publish-wiki:
>   runs-on: ubuntu-latest
>   steps:
>     - uses: actions/checkout@v3
>     - uses: impresscms-dev/strip-markdown-extensions-from-links-action@v1.0.0
>       with:
>         path: wiki
>     - uses: Andrew-Chen-Wang/github-wiki-action@v4
> ```
>
> ❤️ If you have an awesome preprocessor action that you want to add here, let us know! We'd love to add an example.

see a potential version of it: https://github.com/Andrew-Chen-Wang/github-wiki-action/tree/jcbhmr#preprocessing

@ribtoks does this meet with your expectations of this action? thoughts? 🤔

**Comment by jcbhmr** [comment]
@Andrew-Chen-Wang seems to be in support of adding this feature to rewrite markdown links from `./hello.md` to `./hello` so that they work seamlessly from source 👉 wiki, but I think they caved lol 😬

After stepping back for a while, my opinion on whether or not this is in-scope for this action have changed.

> Ok so I've somewhat lessened my opposition on this issue purely due to this project's name. This is "github-wiki-action" after all, so it makes sense to include everything, I guess. In not thrilled about tackling seemingly separate projects all in one thing, but if it fits the goal, i guess it fits the goal. 😕

SO in summary, while it was good to get v4 out and in the wild, I guess now it's time to revisit the goal of what "github-wiki-action"  means. #26  Taken maximally, it does include this feature builtin.

**Comment by jcbhmr** [comment]
To do this, it would seem that it's relatively basic:
1. loop through each file
2. match `/\[([^\]]+)?\]\(([^)]+)\)/g` or `/^\[(.*)\]:\s+(.*?)\s*(".*"|'.*'|\(.*\))?$/gm`
3. $2 += .md
4. replace it!

Actually, that will fail with codeblocks or other stuff like `[](./not-me)` since it's a regex, not a true markdown parser...

To do it the right way, it looks like I need to use something like this:

```js
const visit = require('unist-util-visit');

module.exports = function (options) {

  function visitor(node) {
    if (/\.md$/.test(node.url)) {
      node.url = node.url.replace(/\.md$/, "")
    }
  }

  function transform(tree) {
    visit(tree, ['link', 'linkReference'], visitor);
  }

  return transform;
};
```

https://github.com/Pondorasti/remark-img-links
https://github.com/zslabs/remark-relative-links/tree/master
